import { getServiceRoleClient } from "../../database/supabaseServiceRole";
import { validateGovernanceDecisionInput, validateGovernanceInvocationInput } from "./validation";
import type { GovernanceDecision, GovernanceDecisionInput, GovernanceExecutionLink, GovernanceExecutionLinkInput, GovernanceInvocation, GovernanceInvocationInput } from "./types";
const DUPLICATE = "23505";
const INV_COLUMNS = "id, user_id, organization_id, workspace_id, work_id, connection_id, actor_kind, actor_id, agent_id, on_behalf_of_actor_kind, on_behalf_of_actor_id, action_category, operation, resource_type, resource_identifier, target_provider, attempted_at, created_at";
const DEC_COLUMNS = "id, user_id, invocation_id, evaluated_at, actor_kind_snapshot, actor_id_snapshot, agent_id_snapshot, on_behalf_of_actor_kind_snapshot, on_behalf_of_actor_id_snapshot, action_category_snapshot, operation_snapshot, resource_type_snapshot, resource_identifier_snapshot, target_provider_snapshot, verdict, reason_code, evaluator_version, decision_source, trust_level_snapshot, policy_identifier_snapshot, registry_rule_id_snapshot, registry_rule_revision_snapshot, runs_permission_snapshot, policy_set_fingerprint, approval_id, approval_status, approver_kind, approver_id, approved_at, created_at";
const LINK_COLUMNS = "id, user_id, invocation_id, effective_governance_decision_id, execution_id, linked_at";
function canonical(value: unknown): string {
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`;
  const record = value as Record<string, unknown>;
  return `{${Object.keys(record).sort().map((key) => `${JSON.stringify(key)}:${canonical(record[key])}`).join(",")}}`;
}
const same = (a: unknown, b: unknown) => canonical(a) === canonical(b);
export const toGovernanceInvocation = (r: any): GovernanceInvocation => ({ id:r.id,userId:r.user_id,organizationId:r.organization_id,workspaceId:r.workspace_id,workId:r.work_id,connectionId:r.connection_id,actorKind:r.actor_kind,actorId:r.actor_id,agentId:r.agent_id,onBehalfOfActorKind:r.on_behalf_of_actor_kind,onBehalfOfActorId:r.on_behalf_of_actor_id,actionCategory:r.action_category,operation:r.operation,resourceType:r.resource_type,resourceIdentifier:r.resource_identifier,targetProvider:r.target_provider,attemptedAt:r.attempted_at,createdAt:r.created_at });
export const toGovernanceDecision = (r: any): GovernanceDecision => ({ id:r.id,userId:r.user_id,invocationId:r.invocation_id,evaluatedAt:r.evaluated_at,actorKindSnapshot:r.actor_kind_snapshot,actorIdSnapshot:r.actor_id_snapshot,agentIdSnapshot:r.agent_id_snapshot,onBehalfOfActorKindSnapshot:r.on_behalf_of_actor_kind_snapshot,onBehalfOfActorIdSnapshot:r.on_behalf_of_actor_id_snapshot,actionCategorySnapshot:r.action_category_snapshot,operationSnapshot:r.operation_snapshot,resourceTypeSnapshot:r.resource_type_snapshot,resourceIdentifierSnapshot:r.resource_identifier_snapshot,targetProviderSnapshot:r.target_provider_snapshot,verdict:r.verdict,reasonCode:r.reason_code,evaluatorVersion:r.evaluator_version,decisionSource:r.decision_source,trustLevelSnapshot:r.trust_level_snapshot,policyIdentifierSnapshot:r.policy_identifier_snapshot,registryRuleIdSnapshot:r.registry_rule_id_snapshot,registryRuleRevisionSnapshot:r.registry_rule_revision_snapshot,runsPermissionSnapshot:r.runs_permission_snapshot,policySetFingerprint:r.policy_set_fingerprint,approvalId:r.approval_id,approvalStatus:r.approval_status,approverKind:r.approver_kind,approverId:r.approver_id,approvedAt:r.approved_at,createdAt:r.created_at });
export const toGovernanceExecutionLink = (r: any): GovernanceExecutionLink => ({ id:r.id,userId:r.user_id,invocationId:r.invocation_id,effectiveGovernanceDecisionId:r.effective_governance_decision_id,executionId:r.execution_id,linkedAt:r.linked_at });
export interface GovernanceStoreDeps { getClient: typeof getServiceRoleClient; }
const defaults: GovernanceStoreDeps = { getClient: getServiceRoleClient };
const invocationPayload = (i: GovernanceInvocationInput) => ({ id:i.id,user_id:i.userId,organization_id:i.organizationId,workspace_id:i.workspaceId,work_id:i.workId,connection_id:i.connectionId,actor_kind:i.actorKind,actor_id:i.actorId,agent_id:i.agentId,on_behalf_of_actor_kind:i.onBehalfOfActorKind,on_behalf_of_actor_id:i.onBehalfOfActorId,action_category:i.actionCategory,operation:i.operation,resource_type:i.resourceType,resource_identifier:i.resourceIdentifier,target_provider:i.targetProvider,attempted_at:i.attemptedAt });
// Postgres may render the same timestamptz instant with +00:00 rather than Z.
// Idempotency compares the caller-owned instant, not its database display form.
function normalizeInstantForComparison(value: string | null | undefined): string | null {
  if (value === null || value === undefined) return null;
  const timestamp = Date.parse(value);
  if (Number.isNaN(timestamp)) throw new Error("invalid timestamp reached governance idempotency comparison");
  return new Date(timestamp).toISOString();
}
const invocationComparablePayload = (i: GovernanceInvocationInput) => ({
  ...invocationPayload(i),
  attempted_at: normalizeInstantForComparison(i.attemptedAt),
});
const decisionPayload = (d: GovernanceDecisionInput) => ({ id:d.id,user_id:d.userId,invocation_id:d.invocationId,evaluated_at:d.evaluatedAt,actor_kind_snapshot:d.actorKindSnapshot,actor_id_snapshot:d.actorIdSnapshot,agent_id_snapshot:d.agentIdSnapshot,on_behalf_of_actor_kind_snapshot:d.onBehalfOfActorKindSnapshot,on_behalf_of_actor_id_snapshot:d.onBehalfOfActorIdSnapshot,action_category_snapshot:d.actionCategorySnapshot,operation_snapshot:d.operationSnapshot,resource_type_snapshot:d.resourceTypeSnapshot,resource_identifier_snapshot:d.resourceIdentifierSnapshot,target_provider_snapshot:d.targetProviderSnapshot,verdict:d.verdict,reason_code:d.reasonCode,evaluator_version:d.evaluatorVersion,decision_source:d.decisionSource,trust_level_snapshot:d.trustLevelSnapshot,policy_identifier_snapshot:d.policyIdentifierSnapshot,registry_rule_id_snapshot:d.registryRuleIdSnapshot,registry_rule_revision_snapshot:d.registryRuleRevisionSnapshot,runs_permission_snapshot:d.runsPermissionSnapshot,policy_set_fingerprint:d.policySetFingerprint,approval_id:d.approvalId,approval_status:d.approvalStatus,approver_kind:d.approverKind,approver_id:d.approverId,approved_at:d.approvedAt });
const decisionComparablePayload = (d: GovernanceDecisionInput) => ({
  ...decisionPayload(d),
  evaluated_at: normalizeInstantForComparison(d.evaluatedAt),
  approved_at: normalizeInstantForComparison(d.approvedAt),
});
export async function createGovernanceInvocation(input: GovernanceInvocationInput, deps: GovernanceStoreDeps = defaults): Promise<any> { const v=validateGovernanceInvocationInput(input); if(!v.ok)return{status:"invalid",errors:v.errors}; const c=deps.getClient(); if(!c)return{status:"unavailable"}; const p=invocationPayload(input); const {data,error}=await c.from("tact_governance_invocations").insert(p).select(INV_COLUMNS).single(); if(!error&&data)return{status:"created",invocation:toGovernanceInvocation(data)}; if((error as any)?.code!==DUPLICATE)return{status:"error",message:error?.message??"insert failed"}; const e=await c.from("tact_governance_invocations").select(INV_COLUMNS).eq("id",input.id).eq("user_id",input.userId).maybeSingle(); if(!e.data)return{status:"error",message:"duplicate claim could not be read"}; const existing=toGovernanceInvocation(e.data); return same(invocationComparablePayload(existing),invocationComparablePayload(input))?{status:"already_exists",invocation:existing}:{status:"idempotency_conflict"}; }
export async function appendGovernanceDecision(input: GovernanceDecisionInput, deps: GovernanceStoreDeps = defaults): Promise<any> { const v=validateGovernanceDecisionInput(input); if(!v.ok)return{status:"invalid",errors:v.errors}; const c=deps.getClient(); if(!c)return{status:"unavailable"}; const p=decisionPayload(input); const {data,error}=await c.from("tact_governance_decisions").insert(p).select(DEC_COLUMNS).single(); if(!error&&data)return{status:"created",decision:toGovernanceDecision(data)}; if((error as any)?.code!==DUPLICATE)return{status:"error",message:error?.message??"insert failed"}; const e=await c.from("tact_governance_decisions").select(DEC_COLUMNS).eq("id",input.id).eq("user_id",input.userId).maybeSingle(); if(!e.data)return{status:"error",message:"duplicate claim could not be read"}; const existing=toGovernanceDecision(e.data); return same(decisionComparablePayload(existing),decisionComparablePayload(input))?{status:"already_exists",decision:existing}:{status:"idempotency_conflict"}; }
export async function linkInvocationExecution(input: GovernanceExecutionLinkInput, deps: GovernanceStoreDeps = defaults): Promise<any> { const c=deps.getClient(); if(!c)return{status:"unavailable"}; const {data,error}=await c.from("tact_governance_invocation_execution_links").insert({user_id:input.userId,invocation_id:input.invocationId,effective_governance_decision_id:input.effectiveGovernanceDecisionId??null,execution_id:input.executionId}).select(LINK_COLUMNS).single(); if(!error&&data)return{status:"created",link:toGovernanceExecutionLink(data)}; if((error as any)?.code===DUPLICATE){const e=await c.from("tact_governance_invocation_execution_links").select(LINK_COLUMNS).eq("execution_id",input.executionId).maybeSingle(); if(e.data){const link=toGovernanceExecutionLink(e.data); return link.invocationId===input.invocationId&&link.effectiveGovernanceDecisionId===(input.effectiveGovernanceDecisionId??null)?{status:"already_exists",link}:{status:"execution_already_linked"};}} return{status:"error",message:error?.message??"insert failed"}; }
export async function getGovernanceInvocation(id:string,userId:string,deps:GovernanceStoreDeps=defaults):Promise<GovernanceInvocation|undefined>{const c=deps.getClient();if(!c)return undefined;const {data}=await c.from("tact_governance_invocations").select(INV_COLUMNS).eq("id",id).eq("user_id",userId).maybeSingle();return data?toGovernanceInvocation(data):undefined;}
export async function listGovernanceDecisionsForInvocation(id:string,userId:string,deps:GovernanceStoreDeps=defaults):Promise<GovernanceDecision[]>{const c=deps.getClient();if(!c)return[];const {data}=await c.from("tact_governance_decisions").select(DEC_COLUMNS).eq("invocation_id",id).eq("user_id",userId).order("evaluated_at",{ascending:false});return(data??[]).map(toGovernanceDecision);}
export async function listInvocationExecutionLinks(id:string,userId:string,deps:GovernanceStoreDeps=defaults):Promise<GovernanceExecutionLink[]>{const c=deps.getClient();if(!c)return[];const {data}=await c.from("tact_governance_invocation_execution_links").select(LINK_COLUMNS).eq("invocation_id",id).eq("user_id",userId).order("linked_at",{ascending:false});return(data??[]).map(toGovernanceExecutionLink);}
