import { createHmac, createHash, timingSafeEqual } from "node:crypto";
import { getServiceRoleClient } from "@tact/runs-core/database/supabaseServiceRole";
import type { CaptureExecutionInput, ExecutionProvider } from "@tact/runs-core/tact-execution";

const TOKEN = /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/;
const HEX = /^[a-f0-9]{64}$/;
const MAX_BODY = 256 * 1024;
const FRESHNESS_SECONDS = 300;
type Source = { id: string; user_id: string; source_id: string; provider: ExecutionProvider; source_type: CaptureExecutionInput["sourceType"]; connection_id: string | null; observation_mode: CaptureExecutionInput["observationMode"]; pre_execution_visible: boolean; trust_level: "UNTRUSTED" | "AUTHENTICATED" | "INTERNAL"; status: "ACTIVE" | "DISABLED" | "REVOKED" };
type Key = { id: string; key_id: string; status: "ACTIVE" | "RETIRED" | "REVOKED"; valid_from: string | null; valid_until: string | null };
export type TelemetryFailure = "missing_headers" | "malformed_headers" | "content_digest_mismatch" | "unknown_or_inactive_source" | "unknown_or_inactive_key" | "secret_unavailable" | "signature_invalid" | "timestamp_stale" | "timestamp_future" | "payload_invalid" | "replay_detected" | "receipt_store_unavailable";
export type ExecutionTelemetryPayload = Omit<CaptureExecutionInput, "userId" | "provider" | "sourceType" | "connectionId" | "observationMode" | "preExecutionVisible">;
export type AcceptedTelemetry = { receiptId: string; source: Source; payload: ExecutionTelemetryPayload; receivedAt: string };
function safeToken(value: string | null): value is string { return !!value && TOKEN.test(value); }
function equalHex(a: string, b: string): boolean { const aa = Buffer.from(a, "utf8"); const bb = Buffer.from(b, "utf8"); return aa.length === bb.length && timingSafeEqual(aa, bb); }
function keyFor(sourceId: string, keyId: string): Buffer | null { const raw = process.env.RUNS_TELEMETRY_HMAC_KEYS_JSON; if (!raw) return null; try { const entry = JSON.parse(raw)[`${sourceId}:${keyId}`]; if (typeof entry !== "string") return null; const key = Buffer.from(entry, "base64"); return key.length >= 32 ? key : null; } catch { return null; } }
function payload(raw: Buffer): ExecutionTelemetryPayload | null { try { const v = JSON.parse(raw.toString("utf8")) as Record<string, unknown>; const required = ["externalEventId", "adapterVersion", "actorKind", "actionCategory", "operation"]; if (!required.every((n) => typeof v[n] === "string" && (v[n] as string).length > 0)) return null; return v as unknown as ExecutionTelemetryPayload; } catch { return null; } }
export async function verifyAndClaimTelemetry(request: Request): Promise<{ ok: true; value: AcceptedTelemetry } | { ok: false; reason: TelemetryFailure }> {
  const receivedAtMs = Date.now(); const receivedAt = new Date(receivedAtMs).toISOString(); const sourceId = request.headers.get("x-runs-source-id"); const keyId = request.headers.get("x-runs-key-id"); const timestamp = request.headers.get("x-runs-timestamp"); const nonce = request.headers.get("x-runs-nonce"); const contentHash = request.headers.get("x-runs-content-sha256"); const signature = request.headers.get("x-runs-signature");
  if (!sourceId || !keyId || !timestamp || !nonce || !contentHash || !signature) return { ok: false, reason: "missing_headers" };
  if (!safeToken(sourceId) || !safeToken(keyId) || !safeToken(nonce) || !HEX.test(contentHash) || !HEX.test(signature) || !/^\d{1,12}$/.test(timestamp)) return { ok: false, reason: "malformed_headers" };
  const raw = Buffer.from(await request.arrayBuffer()); if (raw.length > MAX_BODY) return { ok: false, reason: "payload_invalid" }; const actualHash = createHash("sha256").update(raw).digest("hex"); if (!equalHex(actualHash, contentHash)) return { ok: false, reason: "content_digest_mismatch" };
  const client = getServiceRoleClient(); if (!client) return { ok: false, reason: "receipt_store_unavailable" };
  const { data: sourceData } = await client.from("tact_telemetry_sources").select("*").eq("source_id", sourceId).maybeSingle(); const source = sourceData as Source | null; if (!source || source.status !== "ACTIVE") return { ok: false, reason: "unknown_or_inactive_source" };
  const { data: keyData } = await client.from("tact_telemetry_source_keys").select("*").eq("source_id", source.id).eq("key_id", keyId).maybeSingle(); const key = keyData as Key | null; if (!key || key.status !== "ACTIVE" || (key.valid_from && Date.parse(key.valid_from) > receivedAtMs) || (key.valid_until && Date.parse(key.valid_until) <= receivedAtMs)) return { ok: false, reason: "unknown_or_inactive_key" };
  const secret = keyFor(sourceId, keyId); if (!secret) return { ok: false, reason: "secret_unavailable" }; const canonical = ["runs-hmac-v1", request.method.toUpperCase(), new URL(request.url).pathname, sourceId, keyId, timestamp, nonce, contentHash].join("\n"); const expected = createHmac("sha256", secret).update(canonical).digest("hex"); if (!equalHex(expected, signature)) return { ok: false, reason: "signature_invalid" };
  const timestampMs = Number(timestamp) * 1000; if (timestampMs < receivedAtMs - FRESHNESS_SECONDS * 1000) return { ok: false, reason: "timestamp_stale" }; if (timestampMs > receivedAtMs + FRESHNESS_SECONDS * 1000) return { ok: false, reason: "timestamp_future" }; const parsed = payload(raw); if (!parsed) return { ok: false, reason: "payload_invalid" };
  const nonceHash = createHash("sha256").update(nonce).digest("hex"); const { data: receipt, error } = await client.from("tact_telemetry_receipts").insert({ user_id: source.user_id, telemetry_source_id: source.id, telemetry_source_key_id: key.id, received_at: receivedAt, request_timestamp: new Date(timestampMs).toISOString(), nonce_hash: nonceHash, content_sha256: actualHash, trust_level_snapshot: source.trust_level, source_id_snapshot: sourceId, key_id_snapshot: keyId }).select("id").single();
  if (error) return { ok: false, reason: (error as { code?: string }).code === "23505" ? "replay_detected" : "receipt_store_unavailable" }; return { ok: true, value: { receiptId: (receipt as { id: string }).id, source, payload: parsed, receivedAt } };
}
export async function linkReceiptToExecution(receiptId: string, executionId: string, userId: string): Promise<boolean> { const client = getServiceRoleClient(); if (!client) return false; const { error } = await client.from("tact_telemetry_receipt_execution_links").insert({ receipt_id: receiptId, execution_id: executionId, user_id: userId }); return !error; }
export function trustedCaptureInput(accepted: AcceptedTelemetry): CaptureExecutionInput { const { source, payload: p, receivedAt } = accepted; return { ...p, userId: source.user_id, provider: source.provider, sourceType: source.source_type, connectionId: source.connection_id, observationMode: source.observation_mode, preExecutionVisible: source.pre_execution_visible, observedAt: p.observedAt ?? receivedAt }; }
