export function buildOutputsSection(
  outputs?: Record<string, unknown>
) {

  if (
    !outputs ||
    Object.keys(outputs).length === 0
  ) {

    return `
========================
Outputs From Other Agents
========================

None

No Agent outputs are available yet.
`;

  }

  const text = Object.entries(outputs)

    .map(([agent, output]) => {

      return `
========================
${agent.toUpperCase()}

${JSON.stringify(
  output,
  null,
  2
)}
`;

    })

    .join("\n");

  return `
========================
Outputs From Other Agents
========================

These are reference outputs
generated by previous Agents.

Use them only as supporting context.

Research Evidence always has higher priority.

${text}
`;

}