/* Local-only SOR-8A security proof. It creates synthetic local users only. */
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { createHash, createHmac, randomUUID } from "node:crypto";
import { createClient } from "@supabase/supabase-js";
import { NextRequest } from "next/server";
import type { CanonicalExecution } from "@tact/runs-core/tact-execution";
import { ingestSignedTelemetry, type SignedTelemetryIngestDeps } from "../app/api/tact/runs/ingest/execution/route";
import type { AcceptedTelemetry } from "../lib/telemetry/executionTelemetry";

function requireEnv(name: string): string { const value = process.env[name]; if (!value) throw new Error(`${name} required`); return value; }
const url = requireEnv("SUPABASE_URL"), serviceKey = requireEnv("SUPABASE_SERVICE_ROLE_KEY"), anonKey = requireEnv("SUPABASE_ANON_KEY");
const admin = createClient(url, serviceKey, { auth: { autoRefreshToken: false, persistSession: false } });
const sourceId = `sor8a-${randomUUID()}`, keyId = "k1", secret = Buffer.from("sor8a-local-only-hmac-secret-at-least-32-bytes"), path = "/api/tact/runs/ingest/execution";
const required = new Set(["fixture source/key","valid request accepted","tenant binding","provider authority","source type authority","connection/source registry authority","missing signature rejected","bad signature rejected","changed body rejected","stale rejected","future rejected","unknown source rejected","disabled source rejected","revoked source rejected","unknown key rejected","revoked key rejected","expired/retired key rejected","missing HMAC secret fails closed","malformed RUNS_TELEMETRY_HMAC_KEYS_JSON fails closed","atomic replay","multi receipt stable execution","different event distinct execution","receipt before capture","work-independent null workId ingest","permission before correlation","correlation failure does not undo security path","no secret leakage","tenant RLS read isolation","schema tables","schema RLS","schema no browser writes","schema tenant FKs","schema no secret material","schema replay uniqueness","canonical execution dedupe unchanged","multi-receipt schema allowed"]);
const passed = new Set<string>();
function check(name: string, value: unknown) { assert.ok(required.has(name), `unexpected check: ${name}`); assert.ok(value, name); assert.ok(!passed.has(name), `duplicate check: ${name}`); passed.add(name); console.log(`PASS ${name}`); }
const payload = (event = `event-${randomUUID()}`) => ({ externalEventId: event, adapterVersion: "sor8a-test-v1", actorKind: "service", actionCategory: "update", operation: "sor8a_test", status: "succeeded", workId: null });
function signed(body: Record<string, unknown>, o: { nonce?: string; timestamp?: string; source?: string; key?: string; headers?: Record<string, string | undefined> } = {}) {
  const nonce = o.nonce ?? randomUUID(), timestamp = o.timestamp ?? Math.floor(Date.now() / 1000).toString(), sid = o.source ?? sourceId, kid = o.key ?? keyId, raw = JSON.stringify(body), digest = createHash("sha256").update(raw).digest("hex");
  const signature = createHmac("sha256", secret).update(["runs-hmac-v1","POST",path,sid,kid,timestamp,nonce,digest].join("\n")).digest("hex");
  const headers: Record<string, string> = { "content-type": "application/json", "x-runs-source-id": sid, "x-runs-key-id": kid, "x-runs-timestamp": timestamp, "x-runs-nonce": nonce, "x-runs-content-sha256": digest, "x-runs-signature": signature };
  for (const [key, value] of Object.entries(o.headers ?? {})) { if (value === undefined) delete headers[key]; else headers[key] = value; }
  return new NextRequest(new URL(path, url).toString(), { method: "POST", headers, body: raw });
}
type CountFilter = readonly [column: string, value: string | null];
async function count(table: string, filters: readonly CountFilter[]) { let query = admin.from(table).select("*", { count: "exact", head: true }); for (const [column, value] of filters) query = query.eq(column, value); const { count } = await query; return count ?? 0; }
function hasCorrelationFailureLog(args: readonly unknown[]): boolean { const detail = args[1]; return args[0] === "[runs/execution-ingest] work correlation failed" && typeof detail === "object" && detail !== null && "errorKind" in detail && detail.errorKind === "Error"; }
function sql(query: string) { return execFileSync("docker", ["exec","supabase_db_yolna-runs","psql","-U","postgres","-d","postgres","-At","-c",query], { encoding: "utf8" }).trim(); }
function schemaProof() {
  const tables = sql("select string_agg(tablename, ',' order by tablename) from pg_tables where schemaname='public' and tablename like 'tact_telemetry_%'");
  check("schema tables", ["tact_telemetry_receipt_execution_links","tact_telemetry_receipts","tact_telemetry_source_keys","tact_telemetry_sources"].every(n => tables.includes(n)));
  check("schema RLS", sql("select count(*) from pg_class where relnamespace='public'::regnamespace and relname in ('tact_telemetry_sources','tact_telemetry_source_keys','tact_telemetry_receipts','tact_telemetry_receipt_execution_links') and relrowsecurity") === "4");
  check("schema no browser writes", sql("select count(*) from pg_policies where schemaname='public' and tablename in ('tact_telemetry_sources','tact_telemetry_source_keys','tact_telemetry_receipts','tact_telemetry_receipt_execution_links') and cmd in ('INSERT','UPDATE','DELETE','ALL') and (roles @> array['anon']::name[] or roles @> array['authenticated']::name[])") === "0");
  const fks = sql("select string_agg(pg_get_constraintdef(oid), E'\\n') from pg_constraint where contype='f' and conrelid in ('public.tact_telemetry_source_keys'::regclass,'public.tact_telemetry_receipts'::regclass,'public.tact_telemetry_receipt_execution_links'::regclass)");
  check("schema tenant FKs", ["FOREIGN KEY (source_id, user_id)","FOREIGN KEY (telemetry_source_id, user_id)","FOREIGN KEY (telemetry_source_key_id, user_id)","FOREIGN KEY (receipt_id, user_id)","FOREIGN KEY (execution_id, user_id)"].every(x => fks.includes(x)));
  check("schema no secret material", sql("select count(*) from information_schema.columns where table_schema='public' and table_name in ('tact_telemetry_sources','tact_telemetry_source_keys','tact_telemetry_receipts','tact_telemetry_receipt_execution_links') and column_name ~* '(secret|signature|hmac)'") === "0");
  const unique = sql("select string_agg(pg_get_constraintdef(oid), E'\\n') from pg_constraint where contype='u' and conrelid in ('public.tact_telemetry_sources'::regclass,'public.tact_telemetry_source_keys'::regclass,'public.tact_telemetry_receipts'::regclass)");
  check("schema replay uniqueness", unique.includes("UNIQUE (source_id)") && unique.includes("UNIQUE (source_id, key_id)") && unique.includes("UNIQUE (telemetry_source_id, telemetry_source_key_id, nonce_hash)"));
  check("canonical execution dedupe unchanged", sql("select count(*) from pg_index where indrelid='public.tact_canonical_executions'::regclass and indisunique and pg_get_indexdef(indexrelid) like '%(user_id, provider, external_event_id)%'") === "1");
  const links = sql("select string_agg(pg_get_constraintdef(oid), E'\\n') from pg_constraint where contype='u' and conrelid='public.tact_telemetry_receipt_execution_links'::regclass");
  check("multi-receipt schema allowed", links.includes("UNIQUE (receipt_id, execution_id)") && !links.includes("UNIQUE (execution_id)"));
  console.log("SOR8A_SCHEMA_INTROSPECTION=PASS");
}
async function main() {
  const emailA = `sor8a-a-${randomUUID()}@example.invalid`, emailB = `sor8a-b-${randomUUID()}@example.invalid`, a = await admin.auth.admin.createUser({ email: emailA, password: "sor8a-local-password", email_confirm: true }), b = await admin.auth.admin.createUser({ email: emailB, password: "sor8a-local-password", email_confirm: true });
  if (!a.data.user || !b.data.user) throw new Error("synthetic user creation failed");
  const userA = a.data.user.id, userB = b.data.user.id; process.env.RUNS_TELEMETRY_HMAC_KEYS_JSON = JSON.stringify({ [`${sourceId}:${keyId}`]: secret.toString("base64") });
  try {
    const source = await admin.from("tact_telemetry_sources").insert({ user_id:userA,source_id:sourceId,provider:"slack",source_type:"sdk_callback",connection_id:null,observation_mode:"instrumented",pre_execution_visible:true,trust_level:"AUTHENTICATED",status:"ACTIVE" }).select("id").single();
    if (!source.data) throw new Error("fixture source creation failed");
    const sourceRecord = source.data, key = await admin.from("tact_telemetry_source_keys").insert({ user_id:userA,source_id:sourceRecord.id,key_id:keyId,status:"ACTIVE" }).select("id").single(); check("fixture source/key", !!key.data);
    const first = await ingestSignedTelemetry(signed({ ...payload(), userId:userB, provider:"custom", sourceType:"webhook" })); check("valid request accepted", first.status === 202);
    const firstBody = await first.json() as { executionId: string }, execution = await admin.from("tact_canonical_executions").select("user_id,provider,source_type,connection_id,work_id").eq("id",firstBody.executionId).single();
    check("tenant binding", execution.data?.user_id === userA); check("provider authority", execution.data?.provider === "slack"); check("source type authority", execution.data?.source_type === "sdk_callback"); check("connection/source registry authority", execution.data?.connection_id === null); check("work-independent null workId ingest", execution.data?.work_id === null);
    check("missing signature rejected", (await ingestSignedTelemetry(signed(payload(), { headers: { "x-runs-signature":undefined } }))).status === 400); check("bad signature rejected", (await ingestSignedTelemetry(signed(payload(), { headers: { "x-runs-signature":"0".repeat(64) } }))).status === 401);
    const tampered = signed(payload()), raw = await tampered.text(), changed = new NextRequest(new URL(path,url), { method:"POST",headers:tampered.headers,body:raw.replace("sor8a_test","changed") }); check("changed body rejected", (await ingestSignedTelemetry(changed)).status === 401);
    check("stale rejected", (await ingestSignedTelemetry(signed(payload(), { timestamp:(Math.floor(Date.now()/1000)-301).toString() }))).status === 401); const future = await ingestSignedTelemetry(signed(payload(), { timestamp:(Math.floor(Date.now()/1000)+301).toString() })), futureBody = await future.clone().json().catch(() => null) as { error?: unknown } | null; console.log(`FUTURE_REJECT_ACTUAL_STATUS=${future.status}`); if (typeof futureBody?.error === "string") console.log(`FUTURE_REJECT_REASON=${futureBody.error}`); check("future rejected", future.status === 401);
    check("unknown source rejected", (await ingestSignedTelemetry(signed(payload(), { source:`missing-${randomUUID()}` }))).status === 401);
    for (const [status, name] of [["DISABLED","disabled source rejected"],["REVOKED","revoked source rejected"]] as const) { const id=`sor8a-${status.toLowerCase()}-${randomUUID()}`; await admin.from("tact_telemetry_sources").insert({user_id:userA,source_id:id,provider:"slack",source_type:"sdk_callback",trust_level:"AUTHENTICATED",status}); check(name,(await ingestSignedTelemetry(signed(payload(),{source:id}))).status===401); }
    check("unknown key rejected", (await ingestSignedTelemetry(signed(payload(), { key:`missing-${randomUUID()}` }))).status === 401);
    for (const [status, name] of [["REVOKED","revoked key rejected"],["RETIRED","expired/retired key rejected"]] as const) { const id=`sor8a-${status.toLowerCase()}-${randomUUID()}`; await admin.from("tact_telemetry_source_keys").insert({user_id:userA,source_id:sourceRecord.id,key_id:id,status,...(status==="RETIRED"?{valid_until:new Date(Date.now()-60000).toISOString()}: {})}); check(name,(await ingestSignedTelemetry(signed(payload(),{key:id}))).status===401); }
    const validEnv=process.env.RUNS_TELEMETRY_HMAC_KEYS_JSON; if (!validEnv) throw new Error("fixture HMAC secret missing"); delete process.env.RUNS_TELEMETRY_HMAC_KEYS_JSON; check("missing HMAC secret fails closed",(await ingestSignedTelemetry(signed(payload()))).status===401); process.env.RUNS_TELEMETRY_HMAC_KEYS_JSON="{"; check("malformed RUNS_TELEMETRY_HMAC_KEYS_JSON fails closed",(await ingestSignedTelemetry(signed(payload()))).status===401); process.env.RUNS_TELEMETRY_HMAC_KEYS_JSON=validEnv;
    const nonce=randomUUID(), replay=payload(), responses=await Promise.all([ingestSignedTelemetry(signed(replay,{nonce})),ingestSignedTelemetry(signed(replay,{nonce}))]), replayReceipts=await count("tact_telemetry_receipts",[["user_id",userA],["nonce_hash",createHash("sha256").update(nonce).digest("hex")]]), replayExecutions=await count("tact_canonical_executions",[["user_id",userA],["provider","slack"],["external_event_id",replay.externalEventId]]); check("atomic replay",responses.filter(r=>r.status===202).length===1&&responses.filter(r=>r.status===409).length===1&&replayReceipts===1&&replayExecutions<=1);
    const same=payload(), one=await ingestSignedTelemetry(signed(same)), two=await ingestSignedTelemetry(signed(same)), oneBody=await one.json() as {executionId:string}, twoBody=await two.json() as {executionId:string}, receipts=await admin.from("tact_telemetry_receipts").select("id").eq("user_id",userA).eq("source_id_snapshot",sourceId).order("created_at",{ascending:false}).limit(2), receiptIds=(receipts.data??[]).map(r=>r.id), receiptLinks=await admin.from("tact_telemetry_receipt_execution_links").select("receipt_id,execution_id").in("receipt_id",receiptIds);
    check("multi receipt stable execution",one.status===202&&two.status===202&&oneBody.executionId===twoBody.executionId&&receiptIds.length===2&&new Set(receiptIds).size===2&&await count("tact_canonical_executions",[["user_id",userA],["provider","slack"],["external_event_id",same.externalEventId]])===1&&receiptLinks.data?.length===2&&receiptLinks.data.every(l=>l.execution_id===oneBody.executionId));
    const other=await ingestSignedTelemetry(signed(payload())); check("different event distinct execution",other.status===202&&(await other.json() as {executionId:string}).executionId!==oneBody.executionId);
    const failed=payload(), beforeReceipts=await count("tact_telemetry_receipts",[["user_id",userA]]), beforeLinks=await count("tact_telemetry_receipt_execution_links",[["user_id",userA]]), failure=await ingestSignedTelemetry(signed({...failed,actorKind:"invalid"})), failedReceipt=await admin.from("tact_telemetry_receipts").select("id").eq("user_id",userA).order("created_at",{ascending:false}).limit(1).single();
    check("receipt before capture",failure.status===202&&await count("tact_telemetry_receipts",[["user_id",userA]])===beforeReceipts+1&&await count("tact_telemetry_receipt_execution_links",[["user_id",userA]])===beforeLinks&&await count("tact_telemetry_receipt_execution_links",[["receipt_id",failedReceipt.data?.id ?? null]])===0&&await count("tact_canonical_executions",[["user_id",userA],["external_event_id",failed.externalEventId]])===0);
    const order:string[]=[], captured={id:randomUUID(),userId:userA,permissionStatus:"pending"} as unknown as CanonicalExecution, accepted={receiptId:randomUUID(),source:{id:sourceRecord.id,user_id:userA,source_id:sourceId,provider:"slack",source_type:"sdk_callback",connection_id:null,observation_mode:"instrumented",pre_execution_visible:true,trust_level:"AUTHENTICATED",status:"ACTIVE"},payload:payload(),receivedAt:new Date().toISOString()} as unknown as AcceptedTelemetry, logs:unknown[][]=[], oldError=console.error;
    const injectedDeps: SignedTelemetryIngestDeps={verify:async()=>({ok:true,value:accepted}),capture:async()=>{order.push("capture");return {status:"captured",execution:captured};},link:async()=>true,permission:async()=>{order.push("permission");return {status:"unavailable"};},correlation:async()=>{order.push("correlation");throw new Error("injected-correlation-failure");}}; console.error=(...args:unknown[])=>{logs.push(args);};
    try { const response=await ingestSignedTelemetry(signed(payload()),injectedDeps); check("permission before correlation",response.status===202&&order.join(",")==="capture,permission,correlation"); check("correlation failure does not undo security path",response.status===202&&order.includes("capture")&&order.includes("permission")&&logs.some(hasCorrelationFailureLog)); } finally { console.error=oldError; }
    const marker="sor8a-raw-body-leak-marker", leakRequest=signed({...payload(),operation:marker}), fullSignature=leakRequest.headers.get("x-runs-signature"); if (!fullSignature) throw new Error("fixture signature missing"); const hmacKeyset=process.env.RUNS_TELEMETRY_HMAC_KEYS_JSON; if (!hmacKeyset) throw new Error("fixture HMAC keyset missing"); const leak=await ingestSignedTelemetry(leakRequest), leakText=await leak.text(), logged=JSON.stringify(logs); check("no secret leakage",![secret.toString(),fullSignature,hmacKeyset,marker].some(value=>leakText.includes(value)||logged.includes(value)));
    const browser=createClient(url,anonKey,{auth:{autoRefreshToken:false,persistSession:false}}); await browser.auth.signInWithPassword({email:emailB,password:"sor8a-local-password"}); const foreign=await browser.from("tact_telemetry_receipts").select("id").eq("user_id",userA); check("tenant RLS read isolation",!foreign.data||foreign.data.length===0);
    schemaProof(); const missing=[...required].filter(name=>!passed.has(name)); if(missing.length) throw new Error(`required checks missing: ${missing.join(", ")}`); console.log(`SOR8A_FOCUSED_TESTS=${passed.size}/${required.size}`); console.log("TENANT_BINDING=PASS\nSOURCE_METADATA_AUTHORITY=PASS\nATOMIC_REPLAY_BARRIER=PASS\nMULTI_RECEIPT_STABLE_EXECUTION=PASS\nRECEIPT_BEFORE_CAPTURE=PASS\nWORK_INDEPENDENT_SECURITY_PATH=PASS\nNO_SECRET_LEAKAGE=PASS");
  } finally { delete process.env.RUNS_TELEMETRY_HMAC_KEYS_JSON; await admin.auth.admin.deleteUser(userA); await admin.auth.admin.deleteUser(userB); }
}
main().catch(error=>{console.error("SOR8A_FOCUSED_TESTS=FAIL",error instanceof Error?error.message:typeof error);process.exitCode=1;});
