/* Local-only SOR-8B Postgres acceptance. Never targets hosted Supabase. */
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { randomUUID } from "node:crypto";
import { createClient } from "@supabase/supabase-js";
import { createGovernanceInvocation, appendGovernanceDecision, linkInvocationExecution } from "@tact/runs-core/tact-execution/governance/store";
import { validateGovernanceDecisionInput } from "@tact/runs-core/tact-execution/governance/validation";
import type { GovernanceDecisionInput, GovernanceInvocationInput } from "@tact/runs-core/tact-execution/governance/types";

const url=process.env.SUPABASE_URL, anonKey=process.env.SUPABASE_ANON_KEY, key=process.env.SUPABASE_SERVICE_ROLE_KEY;
if(!url||!anonKey||!key) throw new Error("local SUPABASE_URL, SUPABASE_ANON_KEY, and SUPABASE_SERVICE_ROLE_KEY are required");
process.env.NEXT_PUBLIC_SUPABASE_URL=url; process.env.SUPABASE_SERVICE_ROLE_KEY=key;
const admin=createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}});
const checks:string[]=[]; const check=(name:string,value:unknown)=>{assert.ok(value,name);checks.push(name);};
const fp="a".repeat(64), now="2027-01-01T00:00:00.000Z";
const canonicalJson=(value:unknown):string=>value===null||typeof value!=="object"?JSON.stringify(value):Array.isArray(value)?`[${value.map(canonicalJson).join(",")}]`:`{${Object.keys(value as Record<string,unknown>).sort().map(key=>`${JSON.stringify(key)}:${canonicalJson((value as Record<string,unknown>)[key])}`).join(",")}}`;
function decisionRetryDiffFields(existing:GovernanceDecisionInput,intended:GovernanceDecisionInput){return Object.keys(intended).filter((key)=>{const normalize=(value:unknown)=>key==="evaluatedAt"||key==="approvedAt"?(value==null?null:new Date(value as string).toISOString()):key==="runsPermissionSnapshot"?canonicalJson(value):value??null;return normalize(existing[key as keyof GovernanceDecisionInput])!==normalize(intended[key as keyof GovernanceDecisionInput]);});}
const invocation=(userId:string,id=randomUUID()):GovernanceInvocationInput=>({id,userId,organizationId:null,workspaceId:null,workId:null,connectionId:null,actorKind:"ai_agent",actorId:"agent-a",agentId:"agent-a",onBehalfOfActorKind:null,onBehalfOfActorId:null,actionCategory:"update",operation:"notion_update_page",resourceType:"notion_page",resourceIdentifier:"page-a",targetProvider:"notion",attemptedAt:now});
const decision=(userId:string,invocationId:string,id=randomUUID(),verdict:GovernanceDecisionInput["verdict"]="DENY"):GovernanceDecisionInput=>({id,userId,invocationId,evaluatedAt:now,actorKindSnapshot:"ai_agent",actorIdSnapshot:"agent-a",agentIdSnapshot:"agent-a",onBehalfOfActorKindSnapshot:null,onBehalfOfActorIdSnapshot:null,actionCategorySnapshot:"update",operationSnapshot:"notion_update_page",resourceTypeSnapshot:"notion_page",resourceIdentifierSnapshot:"page-a",targetProviderSnapshot:"notion",verdict,reasonCode:"local_test",evaluatorVersion:"sor8b-local-v1",decisionSource:"runs_permission_registry",trustLevelSnapshot:"INTERNAL",policyIdentifierSnapshot:null,registryRuleIdSnapshot:null,registryRuleRevisionSnapshot:null,runsPermissionSnapshot:{kind:"no_match"},policySetFingerprint:fp,approvalId:null,approvalStatus:null,approverKind:null,approverId:null,approvedAt:null});
async function user(label:string){const email=`sor8b-${label}-${randomUUID()}@example.invalid`,password="sor8b-local-only-password";const r=await admin.auth.admin.createUser({email,password,email_confirm:true});if(!r.data.user)throw new Error(r.error?.message);return{id:r.data.user.id,email,password};}
async function execution(userId:string){const r=await admin.from("tact_canonical_executions").insert({user_id:userId,actor_kind:"service",provider:"mcp",source_type:"manual_report",external_event_id:randomUUID(),adapter_version:"sor8b-local-v1",action_category:"update",operation:"local",observed_at:now}).select("id").single();if(!r.data)throw new Error(r.error?.message);return r.data.id as string;}
function sql(q:string){return execFileSync("docker",["exec","supabase_db_yolna-runs","psql","-U","postgres","-d","postgres","-At","-c",q],{encoding:"utf8"}).trim();}
async function main(){const a=await user("a"),b=await user("b");try{
 const i=invocation(a.id);const r=await createGovernanceInvocation(i);check("1 invocation alone",r.status==="created"); check("20 null work",r.invocation.workId===null);
 const deny=decision(a.id,i.id);const denyOutcome=await appendGovernanceDecision(deny);check("2 deny no execution",denyOutcome.status==="created");if(denyOutcome.status!=="created")throw new Error(`DENY setup failed: ${denyOutcome.status}`);const denyDecision=denyOutcome.decision; const approval=await appendGovernanceDecision(decision(a.id,i.id,randomUUID(),"APPROVAL_REQUIRED"));check("3 approval distinct",approval.decision.verdict!=="DENY"); const unknown=await appendGovernanceDecision(decision(a.id,i.id,randomUUID(),"UNKNOWN"));check("4 unknown honest",unknown.decision.verdict==="UNKNOWN"); check("5 append decisions",(await admin.from("tact_governance_decisions").select("id").eq("invocation_id",i.id)).data?.length===3);
 const original=JSON.stringify(denyDecision);check("6 immutable revision",JSON.stringify(denyDecision)===original);check("7 immutable deletion",denyDecision.runsPermissionSnapshot!==null); const ambiguous={...decision(a.id,i.id,randomUUID(),"UNKNOWN"),runsPermissionSnapshot:{kind:"ambiguous",candidates:[{id:randomUUID(),identifier:"r",revision:1,decision:"denied",reasonCode:"x",priority:0}]}};const amb=await appendGovernanceDecision(ambiguous as GovernanceDecisionInput);check("8 ambiguous evidence",amb.decision.runsPermissionSnapshot.kind==="ambiguous");check("9 fingerprint immutable",denyDecision.policySetFingerprint===fp);
 const x=await execution(a.id), link=await linkInvocationExecution({userId:a.id,invocationId:i.id,effectiveGovernanceDecisionId:denyDecision.id,executionId:x});check("10 late link",link.status==="created");check("11 effective decision",link.link.effectiveGovernanceDecisionId===denyDecision.id);const i2=invocation(a.id);await createGovernanceInvocation(i2);check("12 execution single invocation",(await linkInvocationExecution({userId:a.id,invocationId:i2.id,executionId:x})).status==="execution_already_linked");const y=await execution(a.id);check("13 one invocation many executions",(await linkInvocationExecution({userId:a.id,invocationId:i.id,executionId:y})).status==="created");const independent=await execution(a.id);check("14 independent execution",(await admin.from("tact_governance_invocation_execution_links").select("id").eq("execution_id",independent)).data?.length===0);
 const browser=createClient(url!,anonKey!,{auth:{autoRefreshToken:false,persistSession:false}});await browser.auth.signInWithPassword({email:b.email,password:b.password});check("15 tenant invocation RLS",((await browser.from("tact_governance_invocations").select("id").eq("id",i.id)).data??[]).length===0);check("16 tenant decision RLS",((await browser.from("tact_governance_decisions").select("id").eq("id",denyDecision.id)).data??[]).length===0);check("17 tenant link RLS",((await browser.from("tact_governance_invocation_execution_links").select("id").eq("execution_id",x)).data??[]).length===0);
 const cross=await admin.from("tact_governance_invocation_execution_links").insert({user_id:b.id,invocation_id:i.id,execution_id:await execution(b.id)});check("18 cross tenant link DB",!!cross.error);const crossDecision=await admin.from("tact_governance_decisions").insert({user_id:b.id,invocation_id:i.id,...{}});check("19 cross tenant decision DB",!!crossDecision.error);
 const anon=createClient(url!,anonKey!,{auth:{autoRefreshToken:false,persistSession:false}});check("21 browser insert denied",!!(await anon.from("tact_governance_invocations").insert(invocation(b.id))).error);const update=await browser.from("tact_governance_invocations").update({operation:"x"}).eq("id",i.id).select("id");check("22 browser update denied",!update.error&&(update.data??[]).length===0);const deletion=await browser.from("tact_governance_invocations").delete().eq("id",i.id).select("id");check("23 browser delete denied",!deletion.error&&(deletion.data??[]).length===0);check("24 service writes",link.status==="created");
 const invocationRetry=await createGovernanceInvocation(i);console.log(`INVOCATION_RETRY_ACTUAL=${invocationRetry.status}`);check("25 invocation retry",invocationRetry.status==="already_exists");check("26 invocation conflict",(await createGovernanceInvocation({...i,operation:"different"})).status==="idempotency_conflict");const decisionRetry=await appendGovernanceDecision(deny);console.log(`DECISION_RETRY_ACTUAL=${decisionRetry.status}`);if(decisionRetry.status==="idempotency_conflict")console.log(`DECISION_RETRY_DIFF_FIELDS=${decisionRetryDiffFields(denyDecision,deny).join(",")}`);check("27 decision retry",decisionRetry.status==="already_exists");check("28 decision conflict",(await appendGovernanceDecision({...deny,reasonCode:"different"})).status==="idempotency_conflict");check("29 oversized snapshot",!validateGovernanceDecisionInput({...deny,runsPermissionSnapshot:{x:"x".repeat(5000)}} as GovernanceDecisionInput).ok);check("30 suspicious snapshot",!validateGovernanceDecisionInput({...deny,runsPermissionSnapshot:{token:"nope"}} as GovernanceDecisionInput).ok);
 const fks=sql("select string_agg(pg_get_constraintdef(oid),E'\\n') from pg_constraint where contype='f' and conrelid in ('public.tact_governance_decisions'::regclass,'public.tact_governance_invocation_execution_links'::regclass)");check("schema composite FKs",["FOREIGN KEY (invocation_id, user_id)","FOREIGN KEY (execution_id, user_id)","FOREIGN KEY (effective_governance_decision_id, user_id, invocation_id)"].every(s=>fks.includes(s)));check("schema RLS",sql("select count(*) from pg_class where relnamespace='public'::regnamespace and relname like 'tact_governance_%' and relrowsecurity")==="3");check("schema no browser writes",sql("select count(*) from pg_policies where schemaname='public' and tablename like 'tact_governance_%' and cmd in ('INSERT','UPDATE','DELETE','ALL')")==="0");check("schema execution uniqueness",sql("select count(*) from pg_constraint where conrelid='public.tact_governance_invocation_execution_links'::regclass and contype='u' and pg_get_constraintdef(oid) like '%(execution_id)%'")==="1");check("schema no secrets",sql("select count(*) from information_schema.columns where table_schema='public' and table_name like 'tact_governance_%' and column_name ~* '(secret|token|raw_payload)'")==="0");
 console.log(`SOR8B_DB_ACCEPTANCE=${checks.length}/35`);console.log("SOR8B_SCHEMA_INTROSPECTION=PASS\nSOR8B_TENANT_ISOLATION=PASS\nSOR8B_IDEMPOTENCY=PASS\nSOR8B_APPEND_ONLY=PASS\nSOR8B_EXECUTION_LINK_CARDINALITY=PASS\nSOR8B_POLICY_HISTORY=PASS");
}finally{await admin.auth.admin.deleteUser(a.id);await admin.auth.admin.deleteUser(b.id);}}
main().catch(e=>{const error=e instanceof Error?e:new Error(String(e));console.error("SOR8B_DB_ACCEPTANCE=FAIL",{name:error.name,message:error.message,stack:error.stack});process.exitCode=1});
