import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { workLabelPresentation } from "../components/runs/ExecutionIdentity";

const root = process.cwd();
const read = (path: string) => readFileSync(resolve(root, path), "utf8");
const shell = read("components/shell/AppShell.tsx");
const secondary = read("components/shell/SecondarySidebar.tsx");
const shellContainers = read("components/shell/ShellContainers.tsx");
const management = read("components/runs/ManagementSidebar.tsx");
const runsSection = read("components/runs/RunsSection.tsx");
const inspector = read("components/runs/ExecutionInspector.tsx");
const attention = read("components/runs/AttentionInbox.tsx");
const attentionSummary = read("components/runs/AttentionSummaryRow.tsx");
const activity = read("components/runs/ActivityTable.tsx");
const executionIdentity = read("components/runs/ExecutionIdentity.tsx");
const icons = read("components/icons/RunsIcons.tsx");
const home = read("components/runs/HomeView.tsx");
const connectionObservation = read("components/runs/ConnectionObservationView.tsx");
const agentManagement = read("components/runs/AgentManagementView.tsx");
const filterSheet = read("components/runs/ActivityFilterSheet.tsx");
const detailPeek = read("components/shell/DetailPeek.tsx");

assert.match(shell, /ShellLayoutMode = "wide" \| "medium" \| "narrow"/);
assert.match(shell, /ShellOverlay = "none" \| "primary" \| "secondary" \| "peek"/);
assert.match(shell, /min-\[1200px\]:static/);
assert.match(shell, /fixed inset-0 z-40/);
assert.match(shell, /focus-visible:ring-2/);
assert.match(shell, /CogIcon/);
assert.doesNotMatch(shell, /SettingsIcon/);
assert.match(icons, /CogIcon[\s\S]*circle cx="8" cy="8" r="2\.1"/);
assert.match(secondary, /min-\[768px\]:static/);
assert.match(secondary, /persistentDesktop \|\| overlay === "secondary"/);
assert.match(secondary, /-translate-x-full/);
assert.match(secondary, /openOverlay\("secondary"/);
assert.doesNotMatch(shellContainers, /lg:static/);
for (const subsection of ["agent", "permission", "connection", "observation"]) assert.match(management, new RegExp(`id: "${subsection}"`));
assert.match(runsSection, /section === "management" && <ManagementSidebar/);
assert.match(runsSection, /mode=\{managementSection\}/);
assert.doesNotMatch(runsSection, /<AgentSidebar|<PermissionSidebar|<ConnectionObservationSidebar/);

assert.match(home, /<h1 className="sr-only">ホーム<\/h1>/);
assert.match(home, /lg:grid-cols-2/);
assert.match(home, /<AttentionSummaryRow/);
assert.match(home, /onSelectAttention\(item\.attentionId\)/);
assert.match(home, /onSelectExecution\(item\.executionId\)/);
assert.match(home, /text-runs-warning">\{attention\.length\}/);
assert.doesNotMatch(home, /CaptureGap|ObservationSurface|観測カバレッジ/);
assert.match(attention, /<AttentionSummaryRow/);
assert.match(attention, /inlineOnWide/);
assert.match(attention, /min-\[1440px\]:flex/);
assert.match(attention, /attentionPrimaryAction\(item\)/);
assert.doesNotMatch(attention, /attentionReasonJapaneseExplanation/);
assert.match(attentionSummary, /attentionReviewPresentation\(item\)/);
assert.match(attentionSummary, /<ExecutionIdentity/);
assert.match(attentionSummary, /workLabel=\{item\.workTitle\}/);
assert.match(attentionSummary, /review\.label/);
assert.doesNotMatch(attentionSummary, /agentLabel|principalLabel/);
assert.match(attentionSummary, /variant === "expanded"/);
assert.match(attentionSummary, /layout=\{variant === "expanded" \? "attention" : "compact"\}/);
assert.match(executionIdentity, /対象：未観測/);
assert.match(executionIdentity, /Work未割り当て/);
assert.equal(workLabelPresentation(null), "Work未割り当て");
assert.equal(workLabelPresentation("関連付け済みWork"), "関連付け済みWork");
assert.match(executionIdentity, /attention\.classification/);
assert.match(executionIdentity, /layout !== "compact"/);
assert.match(executionIdentity, /min-\[1024px\]:grid-cols/);
assert.doesNotMatch(executionIdentity, /post_execution/);
assert.match(activity, /layout="activity"/);
assert.match(activity, /aria-hidden="true"/);
assert.match(activity, /min-\[1024px\]:grid/);
assert.match(secondary, /compact \? "min-\[768px\]:w-\[184px\]/);
assert.match(runsSection, /<SecondarySidebar title="要確認" compact>/);
assert.match(inspector, /model\.summary\.resource \?\? "未観測"/);

assert.match(runsSection, /preserveSelectionRef/);
assert.match(runsSection, /setSelectedWorkId\(null\)/);
assert.match(runsSection, /setSelectedAttentionId\(attentionId\)/);
assert.match(runsSection, /setInspectedExecutionId\(executionId\)/);
assert.match(detailPeek, /role=\{narrow \? "dialog" : "complementary"\}/);
assert.match(detailPeek, /aria-modal=\{narrow \|\| undefined\}/);
assert.match(detailPeek, /inlineOnWide/);
assert.match(detailPeek, /min-\[1440px\]:static/);
assert.doesNotMatch(detailPeek, /md:block/);
assert.match(runsSection, /<ActivityFilterSheet open=\{activityFilterOpen\}/);
assert.match(filterSheet, /event\.key === "Escape"/);
assert.match(filterSheet, /absolute inset-y-0 right-0/);
assert.match(filterSheet, /if \(!open\) return null/);
assert.match(runsSection, /activityFilterButtonRef\.current\?\.focus\(\)/);
assert.match(connectionObservation, /const isObservation = props.mode === "observation"/);
assert.match(agentManagement, /現在確認できる追加メタデータはありません。/);
assert.match(inspector, /label=/);

console.log("PASS SOR-262 UI architecture v1 contract");
