import type { Provider } from "../../agent/types";
import type { LLMRequest, LLMResponse } from "../../llm/types";
import type {
  AnalysisCapabilityKind,
  AnalysisPurpose,
  CapabilityEvaluation,
  CapabilityEvaluationInput,
  CapabilityRequirementKind,
  MissingCapabilityRequirement,
} from "../capability/types";
import type { PresentationSuitability } from "../presentation/types";
import type { ValidationIssue } from "../types";

export const MAX_PLAN_STEPS = 5;
export const MAX_PLAN_REASON_LENGTH = 300;

/** Trusted, compact capability view that can be provided to an optional planner LLM. */
export interface PlannerCapabilityDescriptor {
  id: string;
  kind: AnalysisCapabilityKind;
  purposes: readonly AnalysisPurpose[];
  description: string;
  executable: boolean;
  suitability: PresentationSuitability;
  missingRequirements: readonly {
    kind: CapabilityRequirementKind;
    description: string;
  }[];
}

/** All Evidence/Dataset data remains local; the optional LLM receives descriptors only. */
export interface AnalysisPlannerInput {
  objective: string;
  targetEntity?: string;
  purposes: readonly AnalysisPurpose[];
  availableCapabilities: readonly PlannerCapabilityDescriptor[];
  lockedCapabilityIds: readonly string[];
  capabilityInput: CapabilityEvaluationInput;
}

export interface AnalysisPlanCandidateStep {
  /** Optional untrusted local alias for dependencies. Final step IDs are generated by Cortex. */
  id?: string;
  capabilityId: string;
  reason: string;
  dependsOn?: readonly string[];
}

export interface AnalysisPlanCandidate {
  steps: readonly AnalysisPlanCandidateStep[];
}

export interface AnalysisPlanStep {
  id: string;
  capabilityId: string;
  ruleId: string;
  ruleVersion: string;
  purposes: readonly AnalysisPurpose[];
  evaluation: CapabilityEvaluation;
  dependsOn: readonly string[];
  status: "ready" | "blocked";
  reason: string;
}

export interface PlanMissingCapabilityRequirement extends MissingCapabilityRequirement {
  requiredByStepIds: readonly string[];
}

export interface ValidatedAnalysisPlan {
  id: string;
  objective: string;
  purposes: readonly AnalysisPurpose[];
  steps: readonly AnalysisPlanStep[];
  missingRequirements: readonly PlanMissingCapabilityRequirement[];
  warnings: readonly ValidationIssue[];
  executable: boolean;
}

export interface AnalysisPlannerSummary {
  llmUsed: boolean;
  candidateSteps: number;
  acceptedSteps: number;
  rejectedSteps: number;
  readySteps: number;
  blockedSteps: number;
}

export interface AnalysisPlannerResult {
  plan?: ValidatedAnalysisPlan;
  warnings: readonly ValidationIssue[];
  summary: AnalysisPlannerSummary;
}

export type AnalysisPlannerRunLLM = (request: LLMRequest) => Promise<LLMResponse>;

export interface AnalysisPlannerOptions {
  registry?: import("../capability/registry").AnalysisCapabilityRegistry;
  provider?: Provider;
  model?: string;
  runLLMImpl?: AnalysisPlannerRunLLM;
}
